# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PeopleofNY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PeopleofNY
	pod 'AlamofireImage', '~> 3.3'

  target 'PeopleofNYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PeopleofNYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
